from pathlib import Path
files = {
"app/layout.tsx": '''import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Carrega as fontes do Google e define variáveis CSS para uso no layout.
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// Metadata usada pelo Next.js para o título e descrição da página.
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// RootLayout é o layout de toda a aplicação.
// Recebe `children` e aplica estilos globais e fontes.
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
''',

"app/page.tsx": '''// Importação de componentes usados nesta página principal.
import Square from "./components/Square";
import { Quadrado } from "./components/Quadrado";
import { Geo_Form } from "./components/Geo_Form";
import { Person, Person2, Person3 } from "./components/Person";
import { Card } from "./components/Card";
import { Card2 } from "./components/Card_2";
import { Card_2_sem_if_ternario } from "./components/Card_2_sem_if_ternario";
import { Card_3 } from "./components/Card_3_and";
import { people_list } from "./data/people_list";
import { Emoji_Rating } from "./components/Emoji_Rating";
import { Student_Table } from "./components/Student_Table";
import { students } from "./data/students";

// Página principal que renderiza uma coleção de componentes de exemplo.
function Page() {
  return (
    <div>
      <h1 className="font-bold text-2xl">Olá mundo!</h1>
      <h3>Seja bem-vindo</h3>

      {/* Renderização de componentes simples de forma geométrica */}
      <Square />
      <Quadrado />

      {/* Componente que agrupa formas geométricas em um container */}
      <div className="flex gap-2 border-2 p-3">
        <Geo_Form />
      </div>

      {/* Exemplos de uso do componente Person com diferentes props */}
      <Person
        name="Willian"
        avatar="/WhatsApp Image 2026-02-03 at 12.30.09.jpg"
        esposa={{
          nome: "Roberta",
          profissao: "Professora",
          ocupacoes: ["Dona de casa", "Mãe", "Esposa"],
        }}
      />

      <Person2
        name="Jose"
        avatar="/WhatsApp Image 2026-02-03 at 12.30.09.jpg"
        esposa={{
          nome: "Elpidia",
          profissao: "Diarista",
          ocupacoes: ["Mãe", "Avó", "Diarista"],
        }}
      />

      <Person2
        name="Maradona"
        esposa={{
          nome: "Manoela",
          profissao: "Frentista",
          ocupacoes: ["Abastecedora", "Tia", "Honesta"],
        }}
      />

      <Person3
        name="Edson"
        avatar="/WhatsApp Image 2026-02-03 at 12.30.09.jpg"
        esposa={{
          nome: "Amanda",
          profissao: "Protética",
          ocupacoes: ["Mãe", "Tia", "Doceira"],
        }}
      />
    </div>
  );
}

const Page_card2 = () => {
  return (
    <div>
      <h1 className="font-bold text-2xl">Olá mundo, de novo!</h1>
      <h3>Seja bem-vindo, novamente.</h3>
      <Card2 phrase="A vida é bela!" author="Pavel Nedved" />
      <Card2 phrase="O conhecimento é poder!" />
    </div>
  );
};

const Page_card3 = () => {
  return (
    <div>
      <h1 className="font-bold text-2xl">Olá mundo, de novo, e de novo!</h1>
      <h3>Seja bem-vindo, novamente hahaha.</h3>
      <Card_3 phrase="A vida é bela!" autor="Pavel Nedved" />
      <Card_3 phrase="O conhecimento é poder!" />
    </div>
  );
};

const Page_renderizando_listas = () => {
  const programador = people_list.filter((person) => person.profession === "Programador");
  const protetico = people_list.filter((person) => person.profession === "Protético");

  return (
    <div>
      <h1 className="font-bold text-2xl">Olá Mundo!</h1>
      <h3>Renderizando listas com map</h3>

      {people_list.length > 0 && (
        <ul>
          {people_list.map((person) => (
            <li key={person.id}>
              {person.name} - {person.profession} - {person.sexo}
            </li>
          ))}
        </ul>
      )}

      <br />
      <h3>Renderizando apenas programadores</h3>
      {programador.length > 0 ? (
        <ul>
          {programador.map((person) => (
            <li key={person.id}>
              {person.name} - {person.profession} - {person.sexo}
            </li>
          ))}
        </ul>
      ) : (
        <p>Nenhum programador encontrado.</p>
      )}

      <br />
      <h3>Renderizando apenas protéticos</h3>
      {protetico.length > 0 && (
        <ul>
          {protetico.map((person) => (
            <li key={person.id}>
              {person.name} - {person.profession} - {person.sexo}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

const Tabela_de_notas = () => {
  return (
    <div className="container mx-auto w-full h-full bg-black text-white">
      <h1 className="text-5xl ml-5">Lista de estudantes</h1>
      <Student_Table students={students} />
    </div>
  );
};

export default Tabela_de_notas;
''',

"app/estados_eventos/page.tsx": '''"use client";

import { useState } from "react";
import { Custom_Button } from "../components/Custom_Button";
import { Person_2 } from "../types/Person_2";
import { TodoItem } from "../types/TodolItem";
import { photoList } from "../data/photo_List";
import { Photo_Item } from "../components/Photo_Item";
import { Modal } from "../components/Modal";
import { questions } from "../data/questions";
import { Question_Item } from "../components/Question_Item";
import { Results } from "../components/Results";

const Page_estados_eventos_click = () => {
    function handleClick() {
        alert("Botão clicado 1!");
    }

    const handleClick2 = () => {
        alert("Botão clicado 4!");
    }

    return (
        <div className="w-screen h-screen flex justify-center items-center">
            <button
                className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 m-3"
                onClick={handleClick}>
                Clique aqui - Botão 1
            </button>

            <button
                className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 m-3"
                onClick={function click() {
                    alert("Botão clicado 2!");
                }}>
                Clique aqui - Botão 2
            </button>

            <button
                className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 m-3"
                onClick={() => alert("Botão clicado 3!")}
            >
                Clique aqui - Botão 3
            </button>

            <button
                className="px-4 py-2 bg-purple-600 text-white rounded-md hover:bg-purple-700 m-3"
                onClick={handleClick2}>
                Clique aqui - Botão 4
            </button>
        </div>
    );
};

const Page_avisar = () => {
    const avisar = (msg: string) => {
        alert(msg);
    };

    return (
        <div className="w-screen h-screen flex justify-center items-center">
            <button
                onClick={() => avisar("Botão clicado 1!")}
                className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 m-3"
            >
                Clique aqui - Botão 1
            </button>
            <button
                onClick={() => avisar("Botão clicado 2!")}
                className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 m-3"
            >
                Clique aqui - Botão 2
            </button>
        </div>
    );
};

const Page_Botao_Customizado = () => {
    const handle_Button_1 = () => alert("Botão 1 clicado !");
    const handle_Button_2 = () => alert("Botão 2 clicado !");
    const handle_Button_3 = () => alert("Botão 3 clicado !");

    return (
        <div className="w-screen h-screen flex justify-center items-center">
            <Custom_Button label="Botão Customizado 1" onclick={handle_Button_1} />
            <Custom_Button label="Botão Customizado 2" onclick={handle_Button_2} />
            <Custom_Button label="Botão Customizado 3" onclick={handle_Button_3} />
        </div>
    );
};

const Page_formulario = () => {
    const handle_Form_Submit = (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        alert("Formulário 1 enviado !");
    };

    return (
        <div className="w-screen h-screen flex flex-col justify-center items-center bg-black">
            <h1 className="text-5xl mb-3 m-3 text-white">Formulário de Login 1</h1>
            <form onSubmit={handle_Form_Submit}>
                <input type="text" className="bg-gray-200 m-3" />
                <input
                    type="submit"
                    value="Enviar"
                    className="px-4 py-2 bg-gray-500 text-black font-bold rounded-md hover:bg-gray-700"
                />
            </form>

            <h1 className="text-5xl mb-3 m-3 text-white">Formulário de Login 2</h1>
            <form
                onSubmit={(e) => {
                    e.preventDefault();
                    alert("Formulário 2 enviado !");
                }}
            >
                <input type="text" className="bg-gray-200 m-3" />
                <input
                    type="submit"
                    value="Enviar"
                    className="px-4 py-2 bg-gray-500 text-black font-bold rounded-md hover:bg-gray-700"
                />
            </form>
        </div>
    );
};

const Page_State = () => {
    const [show_Secret, setShow_Secret] = useState(false);
    const [count, setCount] = useState(0);

    const handle_Click_Button = () => {
        setCount(count + 1);
    };

    return (
        <div className="w-screen h-screen flex flex-col justify-center items-center text-3xl">
            <p>{count}</p>
            <button
                onClick={handle_Click_Button}
                className="px-4 py-2 bg-gray-500 text-black font-bold rounded-md hover:bg-gray-700 p-3"
            >
                +1
            </button>
            <button
                onClick={() => setShow_Secret(!show_Secret)}
                className="px-4 py-2 bg-green-500 text-black font-bold rounded-md hover:bg-green-700 p-3 m-3"
            >
                {show_Secret ? "Esconder Área Secreta" : "Mostrar Área Secreta"}
            </button>
            {show_Secret && (
                <div className="bg-green-400 p-4 m-3 rounded-md">Área secreta</div>
            )}
        </div>
    );
};

const Page_Manipulando_campo_texto = () => {
    const [nameInput, setNameInput] = useState("");

    const handleBtnClick = () => {
        alert(nameInput);
    };

    return (
        <div className="w-screen h-screen flex flex-col justify-center items-center text-3xl">
            <input
                type="text"
                className="border border-white bg-gray-50 p-3 text-xl text-black rounded"
                placeholder="Digite seu nome"
                value={nameInput}
                onChange={(e) => setNameInput(e.target.value)}
            />
            <p>Seu nome é: {nameInput}</p>
            <button
                onClick={handleBtnClick}
                className="bg-amber-500 text-black font-bold rounded-md hover:bg-amber-700 p-3 m-3"
            >
                Mostrar valor do campo
            </button>
        </div>
    );
};

const Page_States_Mudando_Tempo = () => {
    const [count, setCount] = useState(0);

    const handleBtnClick = () => {
        setCount(count + 2);
        setCount((c) => c + 2);
        setCount((c) => c + 2);
    };

    return (
        <div className="w-screen h-screen flex flex-col justify-center items-center text-3xl">
            <p>{count}</p>
            <button
                onClick={handleBtnClick}
                className="bg-amber-500 text-black font-bold rounded-md hover:bg-amber-700 p-3 m-3"
            >
                +2
            </button>
        </div>
    );
};

const Page_atualizando_objetos_states = () => {
    const [fullName, setFullName] = useState<Person_2>({
        firstName: "",
        lastName: "",
    });

    const handle_Clear_button_FullName = () => {
        setFullName({ firstName: "", lastName: "" });
    };

    const handle_Clear_button_FirstName = () => {
        setFullName({ ...fullName, firstName: "" });
    };

    const handle_Clear_button_LastName = () => {
        setFullName({ ...fullName, lastName: "" });
    };

    return (
        <div className="w-screen h-screen flex flex-col justify-center items-center text-3xl">
            <input
                type="text"
                placeholder="Nome"
                className="border border-white p-3 text-2xl text-white rounded-md mb-3"
                value={fullName.firstName}
                onChange={(e) => setFullName({ ...fullName, firstName: e.target.value })}
            />
            <input
                type="text"
                placeholder="Sobrenome"
                className="border border-white p-3 text-2xl text-white rounded-md mb-3"
                value={fullName.lastName}
                onChange={(e) => setFullName({ ...fullName, lastName: e.target.value })}
            />
            <p>Meu nome completo é:</p>
            <p>{fullName.firstName} {fullName.lastName}</p>
            <button
                onClick={handle_Clear_button_FullName}
                className="bg-amber-500 text-black font-bold rounded-md hover:bg-amber-700 p-3 m-3"
            >
                Limpar Nome e Sobrenome
            </button>
            <button
                onClick={handle_Clear_button_FirstName}
                className="bg-amber-500 text-black font-bold rounded-md hover:bg-amber-700 p-3 m-3"
            >
                Limpar Nome
            </button>
            <button
                onClick={handle_Clear_button_LastName}
                className="bg-amber-500 text-black font-bold rounded-md hover:bg-amber-700 p-3 m-3"
            >
                Limpar Sobrenome
            </button>
        </div>
    );
};

const Page_Array_States = () => {
    const [itemInput, setItemInput] = useState("");
    const [list, setList] = useState<TodoItem[]>([
        { id: 1, label: "Fazer dever de casa.", checked: true },
        { id: 2, label: "Comprar bolo.", checked: false },
    ]);

    const handle_Add_Button = () => {
        if (itemInput.trim() === "") {
            alert("O campo de tarefa não pode estar vazio.");
            return;
        }
        const newItem: TodoItem = { id: Date.now(), label: itemInput, checked: false };
        setList([...list, newItem]);
        setItemInput("");
    };

    const toggleItem = (index: number) => {
        const newList = [...list];
        newList[index].checked = !newList[index].checked;
        setList(newList);
    };

    const deleteItem = (index: number) => {
        const newList = list.filter((_, i) => i !== index);
        alert(`Item "${list[index].label}" deletado!`);
        setList(newList);
    };

    return (
        <div className="w-screen h-screen flex flex-col justify-center items-center text-2xl">
            <h1 className="text-4xl mt-5">Lista de Tarefas</h1>
            <div className="flex w-full max-w-lg my-3 p-4 rounded-md bg-gray-700 border-2 border-gray-200">
                <input
                    type="text"
                    placeholder="O que deseja fazer?"
                    className="flex-1 border border-black p-3 text-2xl text-blue-900 rounded-md mr-3 bg-white"
                    value={itemInput}
                    onChange={(e) => setItemInput(e.target.value)}
                />
                <button
                    className="bg-amber-500 text-black font-bold rounded-md hover:bg-amber-700 p-3"
                    onClick={handle_Add_Button}
                >
                    Adicionar
                </button>
            </div>
            <p className="my-4">{list.length} Itens na lista</p>
            <ul className="w-full max-w-lg list-disc pl-5">
                {list.map((item, index) => (
                    <li key={item.id} className={`flex items-center mb-2 ${item.checked ? "line-through text-gray-500" : ""}`}>
                        <input
                            type="checkbox"
                            className="w-6 h-6 mr-3"
                            checked={item.checked}
                            onChange={() => {}}
                            onClick={() => toggleItem(index)}
                        />
                        {item.label} -
                        <button
                            onClick={() => deleteItem(index)}
                            className="hover:underline"
                        >
                            [Deletar]
                        </button>
                    </li>
                ))}
            </ul>
        </div>
    );
};

const Page_Galeria_Imagens = () => {
    const [showModal, setShowModal] = useState(false);
    const [selectedPhoto, setSelectedPhoto] = useState(photoList[0]);

    const openModal = (photo: typeof photoList[0]) => {
        setSelectedPhoto(photo);
        setShowModal(true);
    };

    const closeModal = () => {
        setShowModal(false);
    };

    return (
        <div className="mx-2">
            <h1 className="text-3xl font-bold my-10 mt-5 text-center">Fotos Intergalácticas</h1>
            <section className="container max-w-5xl mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
                {photoList.map((photo) => (
                    <Photo_Item key={photo.id} photo={photo} onClick={() => openModal(photo)} />
                ))}
            </section>
            {showModal && <Modal image={selectedPhoto.url} closeModal={closeModal} />}
        </div>
    );
};

const Page_Questions = () => {
    const [answers, setAnswers] = useState<number[]>([]);
    const [showResult, setShowResult] = useState(false);
    const [currentQuestion, setCurrentQuestion] = useState(0);
    const title = "Quiz de Culinária";

    const loadNextQuestion = () => {
        if (currentQuestion < questions.length - 1) {
            setCurrentQuestion(currentQuestion + 1);
        } else {
            setShowResult(true);
        }
    };

    const handle_Restar_Button = () => {
        setCurrentQuestion(0);
        setAnswers([]);
        setShowResult(false);
    };

    const handleAnswer = (payload: { correct: boolean; selectedAnswer: number; questionIndex: number }) => {
        setAnswers((prev) => [...prev, payload.selectedAnswer]);
        loadNextQuestion();
    };

    return (
        <div className="w-screen h-screen flex flex-col justify-center items-center text-3xl bg-blue-600 text-white">
            <div className="w-full max-w-xl rounded-md bg-white text-black shadow shadow-black">
                <div className="p-5 font-bold text-2xl border-b border-gray-300">{title}</div>
                <div className="p-5">
                    <Question_Item
                        question={questions[currentQuestion]}
                        count={currentQuestion + 1}
                        onAnswer={handleAnswer}
                    />
                    {showResult && <Results answers={answers} questions={questions} />}
                </div>
                <div className="p-5 text-center border-t border-gray-300">
                    {!showResult && <>{currentQuestion + 1} de {questions.length} pergunta(s) respondida(s)</>}
                    {!showResult && (
                        <button
                            onClick={loadNextQuestion}
                            className="ml-3 px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-700"
                        >
                            Próxima Pergunta
                        </button>
                    )}
                    {!showResult && (
                        <button
                            onClick={() => setShowResult(true)}
                            className="ml-3 px-4 py-2 bg-gray-500 text-white rounded-md hover:bg-gray-700"
                        >
                            Ver Resultado
                        </button>
                    )}
                    <button
                        onClick={handle_Restar_Button}
                        className="ml-3 px-4 py-2 bg-gray-500 text-white rounded-md hover:bg-gray-700 mt-3"
                    >
                        Reiniciar
                    </button>
                </div>
            </div>
        </div>
    );
};

export default Page_Questions;
''',

"app/components/Card.tsx": '''// Card.tsx
// Componente que recebe `children` e o renderiza dentro de uma caixa verde.

type Props = {
    children: React.ReactNode;
};

export const Card = ({ children }: Props) => {
    return (
        <div className="w-96 h-40 bg-green-600 text-black p-3 text-3xl text-center">
            {children}
        </div>
    );
};
''',

"app/components/Card_2.tsx": '''// Card_2.tsx
// Componente que mostra uma frase e um autor opcional.

type Props = {
    phrase: string;
    author?: string;
};

export const Card2 = ({ phrase, author }: Props) => {
    return (
        <div className="w-96 h-40 bg-red-600 text-white p-3 text-3xl text-center italic">
            <h3 className="text-3xl font-bold italic">{phrase}</h3>
            <p className="text-right text-sm">— {author ?? "Autor Desconhecido"}</p>
        </div>
    );
};
''',

"app/components/Card_2_sem_if_ternario.tsx": '''// Card_2_sem_if_ternario.tsx
// Componente que escolhe automaticamente o texto do autor.

type Props = {
    phrase: string;
    author?: string;
};

export const Card_2_sem_if_ternario = ({ phrase, author }: Props) => {
    if (author) {
        return (
            <div className="w-96 h-40 bg-gray-600 text-black p-3 text-3xl text-center italic">
                <h3 className="text-3xl font-bold italic">{phrase}</h3>
                <p className="text-right text-sm">— {author}</p>
            </div>
        );
    }

    return (
        <div className="w-96 h-40 bg-gray-600 text-black p-3 text-3xl text-center italic">
            <h3 className="text-3xl font-bold italic">{phrase}</h3>
            <p className="text-right text-sm">— Autor Desconhecido</p>
        </div>
    );
};
''',

"app/components/Card_3_and.tsx": '''// Card_3_and.tsx
// Componente que renderiza uma frase e mostra o autor apenas quando existe.

type Props = {
    phrase: string;
    autor?: string;
};

export const Card_3 = ({ phrase, autor }: Props) => {
    return (
        <div className="w-80 border-2 border-gray-600 text-center italic p-4">
            <h3 className="text-lg font-semibold">{phrase}</h3>
            {autor ? (
                <p className="text-right text-sm">-{autor}</p>
            ) : (
                <p className="text-right text-sm italic">-Autor desconhecido</p>
            )}
        </div>
    );
};
''',

"app/components/Custom_Button.tsx": '''// Custom_Button.tsx
// Componente de botão reutilizável que aceita texto e callback de clique.

type Props = {
    label: string;
    onclick?: () => void;
};

export const Custom_Button = ({ label, onclick }: Props) => {
    return (
        <button
            onClick={onclick}
            className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 m-3"
        >
            {label}
        </button>
    );
};
''',

"app/components/Emoji_Rating.tsx": '''// Emoji_Rating.tsx
// Componente que mostra uma nota e transforma em emoji.

type Props = {
    rating: number;
};

export const Emoji_Rating = ({ rating }: Props) => {
    if (rating < 0) rating = 0;
    if (rating > 5) rating = 5;

    const rateInt = Math.floor(rating);
    const emojis = ["😡", "😞", "😐", "😊", "😍"];
    const selectedEmoji = emojis[rateInt - 1] || emojis[0];
    const hasHalfStar = rating - rateInt >= 0.5;
    const halfStar = hasHalfStar ? "⭐" : "";

    return (
        <div className="flex items-center text-6xl">
            <div className="bg-gray-700 p-2 rounded">{rating.toFixed(1)}</div>
            <div className="ml-3">{selectedEmoji}{halfStar}</div>
        </div>
    );
};
''',

"app/components/Geo_Form.tsx": '''// Geo_Form.tsx
// Componente que mostra dois elementos geométricos juntos.

import { Quadrado } from "./Quadrado";
import Square from "./Square";

export const Geo_Form = () => {
    return (
        <div>
            <h3 className="text-2xl font-bold">Formas geométricas</h3>
            <Square />
            <Quadrado />
        </div>
    );
};
''',

"app/components/Modal.tsx": '''// Modal.tsx
// Componente que exibe uma imagem em tela cheia.

type ModalProps = {
    image: string;
    closeModal: () => void;
};

export const Modal = ({ image, closeModal }: ModalProps) => {
    return (
        <>
            <div
                onClick={closeModal}
                className="fixed top-0 left-0 right-0 bottom-0 flex items-center justify-center bg-black/90"
            >
                <img src={image} alt="Modal" className="max-w-full max-h-full" />
            </div>
            <div
                onClick={closeModal}
                className="fixed top-5 right-5 cursor-pointer text-white text-5xl"
            >
                Close
            </div>
        </>
    );
};
''',

"app/components/Person.tsx": '''// Person.tsx
// Componentes para exibir pessoa e dados da esposa.

type Esposa = {
    nome: string;
    profissao: string;
    ocupacoes: string[];
};

type Prosp = {
    name: string;
    avatar?: string;
    esposa: Esposa;
};

const getWeekDay = (day: number): string => {
    const weekDays = [
        "Domingo",
        "Segunda-feira",
        "Terça-feira",
        "Quarta-feira",
        "Quinta-feira",
        "Sexta-feira",
        "Sábado",
    ];
    return weekDays[day];
};

export const Person = (props: Prosp) => {
    const { name, avatar, esposa } = props;

    return (
        <>
            <h1>{name}</h1>
            <img src={avatar} alt={name} className="w-40" />
            <ul>
                <li>Nome: {esposa.nome}</li>
                <li>Profissão: {esposa.profissao}</li>
                <li>Ocupações:</li>
                {esposa.ocupacoes.map((ocupacao, index) => (
                    <li key={index}>{ocupacao}</li>
                ))}
            </ul>
        </>
    );
};

export const Person2 = ({
    name,
    avatar = "https://png.pngtree.com/element_our/20200610/ourlarge/pngtree-black-default-avatar-image_2237212.jpg",
    esposa,
}: Prosp) => {
    return (
        <>
            <h1>{name}</h1>
            <img src={avatar} alt={name} className="w-40" />
            <ul>
                <li>Nome: {esposa.nome}</li>
                <li>Profissão: {esposa.profissao}</li>
                <li>Ocupações:</li>
                {esposa.ocupacoes.map((ocupacao, index) => (
                    <li key={index}>{ocupacao}</li>
                ))}
            </ul>
        </>
    );
};

export const Person3 = (props: Prosp) => {
    const name = "Willian";
    const avatar = "/WhatsApp Image 2026-02-03 at 12.30.09.jpg";
    const esposa = {
        nome: "Roberta",
        profissao: "Professora",
        ocupacoes: ["Dona de casa", "Mãe", "Esposa"],
    };

    return (
        <>
            <h1 style={{ color: "red", fontSize: "1.5rem" }}>
                Nome: {name} - {getWeekDay(new Date().getDay())}
            </h1>
            <p>Nome: João</p>
            <p>Idade: 30 anos</p>
            <p>Profissão: Desenvolvedor</p>
            <img src={avatar} alt={name} className="w-60 h-60" />
            <p>Nome: {esposa.nome}</p>
            <p>Profissão: {esposa.profissao}</p>
            <p>Ocupações:</p>
            <ul className="font-bold">
                {esposa.ocupacoes.map((ocupacao, index) => (
                    <li key={index}>{ocupacao}</li>
                ))}
            </ul>
        </>
    );
};
''',

"app/components/Photo_Item.tsx": '''// Photo_Item.tsx
// Componente que exibe uma foto e chama onClick quando o usuário clica.

import Image from "next/image";
import { Photo } from "../types/Photo";

type Props = {
    photo: Photo;
    onClick?: () => void;
};

export const Photo_Item = ({ photo, onClick }: Props) => {
    return (
        <div
            className="w-full h-full flex justify-center items-center cursor-alias hover:opacity-80 transition-opacity"
            onClick={onClick}
        >
            <Image
                src={photo.url}
                alt={`Foto ${photo.id}`}
                width={400}
                height={300}
                className="w-full h-auto object-cover mb-4"
                onClick={onClick}
            />
        </div>
    );
};
''',

"app/components/Quadrado.tsx": '''// Quadrado.tsx
// Componente simples que renderiza um quadrado verde com texto.

export const Quadrado = () => {
    return (
        <div className="w-200 h-20 bg-green-500 text-black">
            Novo texto qualquer inspirador.
        </div>
    );
};
''',

"app/components/Question_Item.tsx": '''"use client";

import { useState } from "react";
import { Question } from "../types/Questions";

type Props = {
    question: Question;
    count: number;
    onAnswer: (payload: { correct: boolean; selectedAnswer: number; questionIndex: number }) => void;
};

export const Question_Item = ({ question, count, onAnswer }: Props) => {
    const [selectedOption, setSelectedOption] = useState<number | null>(null);

    const checkAnswer = (index: number) => {
        if (selectedOption !== null) return;

        const isCorrect = index === question.answer;
        setSelectedOption(index);

        setTimeout(() => {
            onAnswer({ correct: isCorrect, selectedAnswer: index, questionIndex: count - 1 });
            setSelectedOption(null);
        }, 2000);
    };

    return (
        <div>
            <div className="text-3xl font-bold mb-5">
                {count}. {question.questions}
            </div>
            <div>
                {question.options.map((option, index) => {
                    const isSelected = selectedOption === index;
                    const showCorrect = selectedOption !== null && index === question.answer;
                    const className = `border px-3 py-2 rounded-md mb-3 cursor-pointer hover:bg-gray-200 border-gray-300 ${
                        showCorrect ? "bg-green-500 text-white" : isSelected ? "bg-red-500 text-white" : ""
                    }`;

                    return (
                        <div key={index} className={className} onClick={() => checkAnswer(index)}>
                            {option}
                        </div>
                    );
                })}
            </div>
        </div>
    );
};
''',

"app/components/Results.tsx": '''// Results.tsx
// Componente que mostra o resultado das respostas do quiz.

import { Question } from "../types/Questions";

type Props = {
    questions: Question[];
    answers: number[];
};

export const Results = ({ answers, questions }: Props) => {
    return (
        <div className="p-5 text-center">
            {questions.map((question, index) => {
                const isCorrect = question.answer === answers[index];
                const givenAnswer = question.options[answers[index]] || "Sem resposta";

                return (
                    <div key={index} className="mb-4">
                        <h3 className="text-lg font-semibold">{question.questions}</h3>
                        <p className={`text-sm ${isCorrect ? "text-green-500" : "text-red-500"}`}>
                            Você respondeu: {givenAnswer} - {isCorrect ? "Certo" : "Errado"}
                        </p>
                    </div>
                );
            })}
        </div>
    );
};
''',

"app/components/Student_Table.tsx": '''// Student_Table.tsx
// Componente que exibe uma tabela com os alunos.

import { Student } from "../types/Student";

type Props = {
    students: Student[];
};

export const Student_Table = ({ students }: Props) => {
    return (
        <table className="w-full border-collapse border border-gray-700 rounded-b-md">
            <thead>
                <tr className="text-left bg-gray-800 text-white">
                    <th className="border border-gray-700 p-2">Name</th>
                    <th className="border border-gray-700 p-2">Status</th>
                    <th className="border border-gray-700 p-2">Grade 1</th>
                    <th className="border border-gray-700 p-2">Grade 2</th>
                    <th className="border border-gray-700 p-2">Final Grade</th>
                </tr>
            </thead>
            <tbody>
                {students.map((item) => (
                    <tr key={item.id} className="text-black bg-gray-400 border-b border-black">
                        <td className="p-3 flex items-center">
                            <img src={item.avatar} alt={item.name} className="w-10 h-10 rounded-full mr-3" />
                            <div>
                                <div className="font-bold">{item.name}</div>
                                <div>{item.email}</div>
                            </div>
                        </td>
                        <td className="p-3">
                            {item.active ? (
                                <div className="px-2 py-1 inline-block rounded-md border border-green-800 bg-green-600 text-white text-xs">
                                    Active
                                </div>
                            ) : (
                                <div className="px-2 py-1 inline-block rounded-md border border-red-800 bg-red-600 text-white text-xs">
                                    Inactive
                                </div>
                            )}
                        </td>
                        <td className="p-3">{item.grade1.toFixed(1)}</td>
                        <td className="p-3">{item.grade2.toFixed(1)}</td>
                        <td className="p-3 font-bold">
                            {item.active ? ((item.grade1 + item.grade2) / 2).toFixed(1) : "N/A"}
                        </td>
                    </tr>
                ))}
            </tbody>
        </table>
    );
};
''',

"app/components/Square.tsx": '''// Square.tsx
// Componente simples que renderiza um quadrado azul com texto.

const Square = () => {
    return (
        <div className="w-160 h-16 bg-blue-500 text-white">
            Texto qualquer inspirador
        </div>
    );
};

export default Square;
''',

"app/components/Renderizando_listas.tsx": '''// Renderizando_listas.tsx
// Arquivo atualmente contém um componente placeholder.
export const Renderizando_listas = () => null;
''',

"app/data/people_list.ts": '''// people_list.ts
// Lista de pessoas usada em exemplos de renderização.

import { Person } from "../types/Person";

export const people_list: Person[] = [
    { id: 1, name: "Willian", profession: "Programador", sexo: "Masculino" },
    { id: 2, name: "Cida", profession: "Diarista", sexo: "Feminino" },
    { id: 3, name: "Senna", profession: "Piloto", sexo: "Masculino" },
    { id: 4, name: "Antonio", profession: "Médico", sexo: "Masculino" },
    { id: 5, name: "Roberta", profession: "Professora", sexo: "Feminino" },
    { id: 6, name: "Adeilda", profession: "Enfermeira", sexo: "Feminino" },
    { id: 7, name: "Edson", profession: "Protético", sexo: "Masculino" },
    { id: 8, name: "Cicero", profession: "Aposentado", sexo: "Masculino" },
    { id: 9, name: "Amanda", profession: "Protética", sexo: "Feminino" },
    { id: 10, name: "Arthur", profession: "Programador", sexo: "Masculino" },
    { id: 11, name: "Alan", profession: "Protético", sexo: "Masculino" },
];
''',

"app/data/students.ts": '''// students.ts
// Dados de estudantes usados na tabela.

import { Student } from "../types/Student";

export const students: Student[] = [
    {
        id: 1,
        active: true,
        name: "Fulano de Tal",
        email: "fulano@escola.com.br",
        avatar: "https://images.unsplash.com/photo-1547037579-f0fc020ac3be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHJvc3RvfGVufDB8MHwwfHx8Mg%3D%3D&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        grade1: 7.3,
        grade2: 8.1,
    },
    {
        id: 2,
        active: true,
        name: "Ciclano Silva",
        email: "ciclano.silva@escola.com.br",
        avatar: "https://images.unsplash.com/photo-1601233749202-95d04d5b3c00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fHJvc3RvfGVufDB8MHwwfHx8Mg%3D%3D&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        grade1: 2.9,
        grade2: 8.7,
    },
    {
        id: 3,
        active: false,
        name: "Beltrano Matheus",
        email: "beltrano.matheus@escola.com.br",
        avatar: "https://images.unsplash.com/photo-1474176857210-7287d38d27c6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjZ8fHJvc3RvfGVufDB8MHwwfHx8Mg%3D%3D&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        grade1: 8.3,
        grade2: 6.4,
    },
    {
        id: 4,
        active: true,
        name: "Zuflano Caxias",
        email: "zuflano.caxias@escola.com.br",
        avatar: "https://images.unsplash.com/photo-1601576084861-5de423553c0f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzF8fHJvc3RvfGVufDB8MHwwfHx8Mg%3D%3D&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        grade1: 9,
        grade2: 8.1,
    },
    {
        id: 5,
        active: true,
        name: "Turano Pires",
        email: "turano.pires@escola.com.br",
        avatar: "https://images.unsplash.com/photo-1564564244660-5d73c057f2d2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDN8fHJvc3RvfGVufDB8MHwwfHx8Mg%3D%3D&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        grade1: 10,
        grade2: 9.7,
    },
    {
        id: 6,
        active: false,
        name: "Voltano Augusto",
        email: "voltano.augusto@escola.com.br",
        avatar: "https://images.unsplash.com/photo-1611689037241-d8dfe4280f2e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NzN8fHJvc3RvfGVufDB8MHwwfHx8Mg%3D%3D&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
        grade1: 5.5,
        grade2: 6.2,
    },
];
''',

"app/data/questions.ts": '''// questions.ts
// Perguntas usadas no quiz de culinária.

import { Question } from "../types/Questions";

export const questions: Question[] = [
    {
        questions: "Qual ingrediente não pode faltar?",
        options: ["Farinha", "Ovo", "Leite", "Açúcar", "Corante"],
        answer: 4,
    },
    {
        questions: "Qual melhor método de cozinhar?",
        options: ["Microondas", "Fogão", "Fogueira", "Lança-chamas", "Fogão a lenha"],
        answer: 3,
    },
    {
        questions: "Qual melhor ingrediente para fazer omelete?",
        options: ["Pena de galinha", "Ovo", "Crista de galo", "Rabo de coiote", "Baleia Zumbi"],
        answer: 1,
    },
];
''',

"app/data/photo_List.ts": '''// photo_List.ts
// Lista de fotos usada pela galeria.

import { Photo } from "../types/Photo";

export const photoList: Photo[] = [
    { id: 1, url: "/imagens_intergalaticas/1.jpg" },
    { id: 2, url: "/imagens_intergalaticas/2.jpg" },
    { id: 3, url: "/imagens_intergalaticas/3.jpg" },
    { id: 4, url: "/imagens_intergalaticas/4.jpg" },
    { id: 5, url: "/imagens_intergalaticas/5.jpg" },
    { id: 6, url: "/imagens_intergalaticas/6.jpg" },
    { id: 7, url: "/imagens_intergalaticas/7.jpg" },
    { id: 8, url: "/imagens_intergalaticas/8.jpg" },
    { id: 9, url: "/imagens_intergalaticas/9.jpg" },
];
''',

"app/types/Person.ts": '''// Person.ts
// Tipo usado para o array people_list.
export type Person = {
    id: number;
    name: string;
    profession: string;
    sexo: string;
};
''',

"app/types/Person_2.ts": '''// Person_2.ts
// Tipo usado para armazenar o nome e sobrenome em um estado.
export type Person_2 = {
    firstName: string;
    lastName: string;
};
''',

"app/types/Student.ts": '''// Student.ts
// Tipo que descreve os dados de cada estudante.
export type Student = {
    id: number;
    active: boolean;
    name: string;
    email: string;
    avatar: string;
    grade1: number;
    grade2: number;
};
''',

"app/types/Questions.ts": '''// Questions.ts
// Tipo que descreve cada pergunta do quiz.
export type Question = {
    questions: string;
    options: string[];
    answer: number;
};
''',

"app/types/Photo.ts": '''// Photo.ts
// Tipo que descreve cada imagem da galeria.
export type Photo = {
    id: number;
    url: string;
};
''',

"app/types/TodolItem.ts": '''// TodolItem.ts
// Tipo usado para itens de tarefa na lista de tarefas.
export type TodoItem = {
    id: number;
    label: string;
    checked: boolean;
};
''',
}

for relative_path, content in files.items():
    path = Path(relative_path)
    path.write_text(content, encoding="utf-8")
    print(f"Wrote {path}")